# Generated by Django 5.2.16 on 2026-07-23 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_purchase_and_chat_read_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoModerationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_type', models.CharField(choices=[('PRODUCT', 'Product'), ('USER', 'User')], max_length=10)),
                ('target_id', models.UUIDField()),
                ('report_count', models.PositiveIntegerField()),
                ('threshold', models.PositiveIntegerField()),
                ('before_status', models.CharField(max_length=12)),
                ('after_status', models.CharField(max_length=12)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('review_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_auto_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['review_status', 'created_at'], name='market_auto_review_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('target_type', 'target_id'), name='unique_auto_moderation_target')],
            },
        ),
    ]
